baseURL: "https://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "ananke"

contentDir: "content/en"

languages:
    en:
        languageName: English
        weight: 1
        contentDir: "content/en"
    fr:
        languageName: Français
        weight: 2
        contentDir: "content/fr"
    es:
        languageName: Spanish
        weight: 3
        contentDir: "content/es"