baseURL: "https://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "ananke"

contentDir: "content/en"

languages:
    en:
        weight: 1
        languageName: "English"
        contentDir: content/en
    es:
        weight: 2
        languageName: "Español"
        contentDir: content/es
    fr:
        weight: 4
        languageName: "Française"
        contentDir: content/fr
